// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: backend/api/proto/v2/game.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameName int32

const (
	GameName_MENCH GameName = 0
	GameName_SNAKE GameName = 1
)

// Enum value maps for GameName.
var (
	GameName_name = map[int32]string{
		0: "MENCH",
		1: "SNAKE",
	}
	GameName_value = map[string]int32{
		"MENCH": 0,
		"SNAKE": 1,
	}
)

func (x GameName) Enum() *GameName {
	p := new(GameName)
	*p = x
	return p
}

func (x GameName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameName) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_proto_v2_game_proto_enumTypes[0].Descriptor()
}

func (GameName) Type() protoreflect.EnumType {
	return &file_backend_api_proto_v2_game_proto_enumTypes[0]
}

func (x GameName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameName.Descriptor instead.
func (GameName) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_proto_v2_game_proto_rawDescGZIP(), []int{0}
}

type RequestCreateRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsPrivate string  `protobuf:"bytes,3,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	SecretKey string  `protobuf:"bytes,4,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Owner     *Member `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *RequestCreateRoom) Reset() {
	*x = RequestCreateRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_proto_v2_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCreateRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateRoom) ProtoMessage() {}

func (x *RequestCreateRoom) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_v2_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateRoom.ProtoReflect.Descriptor instead.
func (*RequestCreateRoom) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_v2_game_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreateRoom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestCreateRoom) GetIsPrivate() string {
	if x != nil {
		return x.IsPrivate
	}
	return ""
}

func (x *RequestCreateRoom) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *RequestCreateRoom) GetOwner() *Member {
	if x != nil {
		return x.Owner
	}
	return nil
}

type ResponseRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room   *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	IsFull bool  `protobuf:"varint,2,opt,name=isFull,proto3" json:"isFull,omitempty"`
}

func (x *ResponseRoom) Reset() {
	*x = ResponseRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_proto_v2_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRoom) ProtoMessage() {}

func (x *ResponseRoom) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_v2_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRoom.ProtoReflect.Descriptor instead.
func (*ResponseRoom) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_v2_game_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseRoom) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *ResponseRoom) GetIsFull() bool {
	if x != nil {
		return x.IsFull
	}
	return false
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsPrivate string   `protobuf:"bytes,3,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	SecretKey string   `protobuf:"bytes,4,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Owner     *Member  `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Members   *Members `protobuf:"bytes,6,opt,name=members,proto3" json:"members,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_proto_v2_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_v2_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_v2_game_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetIsPrivate() string {
	if x != nil {
		return x.IsPrivate
	}
	return ""
}

func (x *Room) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Room) GetOwner() *Member {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Room) GetMembers() *Members {
	if x != nil {
		return x.Members
	}
	return nil
}

type Members struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*Member `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *Members) Reset() {
	*x = Members{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_proto_v2_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Members) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Members) ProtoMessage() {}

func (x *Members) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_v2_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Members.ProtoReflect.Descriptor instead.
func (*Members) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_v2_game_proto_rawDescGZIP(), []int{3}
}

func (x *Members) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username    string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_proto_v2_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_v2_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_v2_game_proto_rawDescGZIP(), []int{4}
}

func (x *Member) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Member) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RequestGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameName GameName `protobuf:"varint,1,opt,name=gameName,proto3,enum=v2.GameName" json:"gameName,omitempty"`
}

func (x *RequestGame) Reset() {
	*x = RequestGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_proto_v2_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGame) ProtoMessage() {}

func (x *RequestGame) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_v2_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGame.ProtoReflect.Descriptor instead.
func (*RequestGame) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_v2_game_proto_rawDescGZIP(), []int{5}
}

func (x *RequestGame) GetGameName() GameName {
	if x != nil {
		return x.GameName
	}
	return GameName_MENCH
}

type RequestJoinRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SecretKey string  `protobuf:"bytes,2,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Member    *Member `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *RequestJoinRoom) Reset() {
	*x = RequestJoinRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_proto_v2_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestJoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJoinRoom) ProtoMessage() {}

func (x *RequestJoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_v2_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJoinRoom.ProtoReflect.Descriptor instead.
func (*RequestJoinRoom) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_v2_game_proto_rawDescGZIP(), []int{6}
}

func (x *RequestJoinRoom) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestJoinRoom) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *RequestJoinRoom) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type Rooms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *Rooms) Reset() {
	*x = Rooms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_proto_v2_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rooms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rooms) ProtoMessage() {}

func (x *Rooms) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_proto_v2_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rooms.ProtoReflect.Descriptor instead.
func (*Rooms) Descriptor() ([]byte, []int) {
	return file_backend_api_proto_v2_game_proto_rawDescGZIP(), []int{7}
}

func (x *Rooms) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_backend_api_proto_v2_game_proto protoreflect.FileDescriptor

var file_backend_api_proto_v2_game_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x76, 0x32, 0x22, 0x85, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x32, 0x2e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x44, 0x0a,
	0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1c, 0x0a,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x76, 0x32,
	0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x73, 0x46, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x46,
	0x75, 0x6c, 0x6c, 0x22, 0xaf, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x05,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x32,
	0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x25,
	0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x2f, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x12, 0x24, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x46, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x37,
	0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x08, 0x67,
	0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x05,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x2a, 0x20, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x45, 0x4e, 0x43, 0x48, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x4e, 0x41, 0x4b, 0x45, 0x10, 0x01, 0x32, 0xa9, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x6e, 0x63,
	0x68, 0x61, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x15, 0x2e, 0x76, 0x32,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x1a, 0x10, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x30, 0x01, 0x12, 0x26, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x0f, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x1a, 0x09, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x33,
	0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x13, 0x2e, 0x76, 0x32, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x1a,
	0x10, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x30, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_backend_api_proto_v2_game_proto_rawDescOnce sync.Once
	file_backend_api_proto_v2_game_proto_rawDescData = file_backend_api_proto_v2_game_proto_rawDesc
)

func file_backend_api_proto_v2_game_proto_rawDescGZIP() []byte {
	file_backend_api_proto_v2_game_proto_rawDescOnce.Do(func() {
		file_backend_api_proto_v2_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_api_proto_v2_game_proto_rawDescData)
	})
	return file_backend_api_proto_v2_game_proto_rawDescData
}

var file_backend_api_proto_v2_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_backend_api_proto_v2_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_backend_api_proto_v2_game_proto_goTypes = []interface{}{
	(GameName)(0),             // 0: v2.GameName
	(*RequestCreateRoom)(nil), // 1: v2.RequestCreateRoom
	(*ResponseRoom)(nil),      // 2: v2.ResponseRoom
	(*Room)(nil),              // 3: v2.Room
	(*Members)(nil),           // 4: v2.Members
	(*Member)(nil),            // 5: v2.Member
	(*RequestGame)(nil),       // 6: v2.RequestGame
	(*RequestJoinRoom)(nil),   // 7: v2.RequestJoinRoom
	(*Rooms)(nil),             // 8: v2.Rooms
}
var file_backend_api_proto_v2_game_proto_depIdxs = []int32{
	5,  // 0: v2.RequestCreateRoom.owner:type_name -> v2.Member
	3,  // 1: v2.ResponseRoom.room:type_name -> v2.Room
	5,  // 2: v2.Room.owner:type_name -> v2.Member
	4,  // 3: v2.Room.members:type_name -> v2.Members
	5,  // 4: v2.Members.members:type_name -> v2.Member
	0,  // 5: v2.RequestGame.gameName:type_name -> v2.GameName
	5,  // 6: v2.RequestJoinRoom.member:type_name -> v2.Member
	3,  // 7: v2.Rooms.rooms:type_name -> v2.Room
	1,  // 8: v2.MenchasticService.CreateRoom:input_type -> v2.RequestCreateRoom
	6,  // 9: v2.MenchasticService.ListRoom:input_type -> v2.RequestGame
	7,  // 10: v2.MenchasticService.JoinRoom:input_type -> v2.RequestJoinRoom
	2,  // 11: v2.MenchasticService.CreateRoom:output_type -> v2.ResponseRoom
	8,  // 12: v2.MenchasticService.ListRoom:output_type -> v2.Rooms
	2,  // 13: v2.MenchasticService.JoinRoom:output_type -> v2.ResponseRoom
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_backend_api_proto_v2_game_proto_init() }
func file_backend_api_proto_v2_game_proto_init() {
	if File_backend_api_proto_v2_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backend_api_proto_v2_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCreateRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_proto_v2_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_proto_v2_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_proto_v2_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Members); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_proto_v2_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_proto_v2_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_proto_v2_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestJoinRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_proto_v2_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rooms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_api_proto_v2_game_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_api_proto_v2_game_proto_goTypes,
		DependencyIndexes: file_backend_api_proto_v2_game_proto_depIdxs,
		EnumInfos:         file_backend_api_proto_v2_game_proto_enumTypes,
		MessageInfos:      file_backend_api_proto_v2_game_proto_msgTypes,
	}.Build()
	File_backend_api_proto_v2_game_proto = out.File
	file_backend_api_proto_v2_game_proto_rawDesc = nil
	file_backend_api_proto_v2_game_proto_goTypes = nil
	file_backend_api_proto_v2_game_proto_depIdxs = nil
}
